"""Initial migration.

Revision ID: 4c2c0e9b28ea
Revises: 
Create Date: 2023-07-01 16:03:50.027361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c2c0e9b28ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('protocol', sa.String(length=63), nullable=False),
    sa.Column('domain', sa.String(length=127), nullable=False),
    sa.Column('suffix', sa.String(length=63), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=True),
    sa.Column('param', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('filename', sa.String(length=50), nullable=True),
    sa.Column('filedata', sa.LargeBinary(), nullable=True),
    sa.Column('linkstatus', sa.SmallInteger(), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.Column('lasttime', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=127), nullable=False),
    sa.Column('email', sa.String(length=127), nullable=False),
    sa.Column('password', sa.String(length=127), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('links')
    # ### end Alembic commands ###
