"""Initial migration.3

Revision ID: 8a5fe66bf708
Revises: 97f68dc767a0
Create Date: 2023-07-07 20:50:58.662558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a5fe66bf708'
down_revision = '97f68dc767a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('url_id', sa.UUID(), nullable=True),
    sa.Column('url', sa.String(length=511), nullable=False),
    sa.Column('event', sa.String(length=511), nullable=False),
    sa.ForeignKeyConstraint(['url_id'], ['links.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event')
    # ### end Alembic commands ###
