"""Initial migration.8

Revision ID: 9cc9312f9d36
Revises: 47a623288d4b
Create Date: 2023-07-07 22:44:52.492569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cc9312f9d36'
down_revision = '47a623288d4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_constraint('event_link_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'links', ['link_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('event_link_id_fkey', 'links', ['link_id'], ['id'])

    # ### end Alembic commands ###
