version: "3.2"
services:
  monitor_db:
    image: postgres:14.7-alpine
    container_name: monitor_db
    environment: 
      POSTGRES_DB: monitor_db
      POSTGRES_USER: app
      POSTGRES_PASSWORD: 123qwe
    volumes:
      - monitor_db_data:/var/lib/postgresql/data/
    restart: always
    ports:
      - 5432:5432
    networks:
      - monitor_nw

  monitor_redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379
    networks:
      - monitor_nw

volumes:
  monitor_db_data:
  redis_data:
  logs:

networks:
  monitor_nw:
    driver: bridge